### ISSUE TITLE
letsdeploy crashes when partially updating configuration

### ISSUE THREAD

**Issue by Tehem** [transcovo/letsdeploy#27]
Hi,

I tried to deploy configuration changes to preproduction using letsdeploy. I changed three values in letsdeploy-config-preprod files (2 in api-node.json and 1 in stargate.json). 

To deploy change I ran:

`(venv)  (master) tmarcon@hp-tm:~/dev/letsdeploy/letsdeploy$ python config_deploy_changes.py  `

During run, I answered 'n' to all other variables but the one I changed:

`UPDATE ALFRED_PASSWORD: "9723tJV4HpusJAWU7r94gjd4VVLtb52y" ---> "%U9B8T#y{QEwD,pA$vu;p'4#k/Dd7w'#" ? (y/n): n`
`REMOVE PORT: "80" ---> x ? (y/n): n`
`UPDATE DISCOUNT_ENGINE: "legacy" ---> "wallet" ? (y/n): y`
`UPDATE WALLET_ENABLED: "false" ---> "true" ? (y/n): y`
`REMOVE PAYMENT_ENABLE_CASH_PAYMENT: "false" ---> x ? (y/n): n`
`REMOVE REDISCLOUD_URL: "redis://rediscloud:PaAbhR29J7IYE2Tc@pub-redis-14650.us-east-1-3.1.ec2.garantiadata.com:14650" ---> x ? (y/n): n`

At the end, the script crashes and display this message:

```
Traceback (most recent call last):
  File "config_deploy_changes.py", line 5, in <module>
    run()
  File "/home/tmarcon/dev/letsdeploy/letsdeploy/src/scripts/config_deploy_changes.py", line 114, in run
    apply_pending_changes(env, current_app, pending_changes, gateway)
  File "/home/tmarcon/dev/letsdeploy/letsdeploy/src/scripts/config_deploy_changes.py", line 84, in apply_pending_changes
    post_config_change(env, app_name, pending_changes)
  File "/home/tmarcon/dev/letsdeploy/letsdeploy/src/scripts/config_deploy_changes.py", line 76, in post_config_change
    slack.post(env.slack_integration, 'CONFIG UPDATE / %s' % app_name, ':gear:', message, {'app_name': app_name})
TypeError: post() takes 4 positional arguments but 5 were given
```

**Comment by Tehem** [comment]
Follow-up:
Configuration values for api-node where correctly updated, but the one for stargate was not ...

**Comment by rossille** [comment]
@Tehem Fixed
